### ISSUE TITLE
LICENSE.TXT contains HTML source of a GitHub page?

### ISSUE THREAD

**Issue by jffry** [pixelsign/html5-device-mockups#11]
It seems that in commit 02cce0ba5d36e2ef57141adc3a61ff4d71bc953d the contents of LICENSE.TXT got changed to (apparently) the source of the GitHub listing page for LICENSE.TXT instead of the contents.

**Comment by pixelsign** [comment]
Hello, thanks for notifying me about this. It is now changed and corrected.
