### ISSUE TITLE
Demo Page Not Working  - Domain name expired 

### ISSUE THREAD

**Issue by clickclickonsal** [pixelsign/html5-device-mockups#12]
![image](https://cloud.githubusercontent.com/assets/8260678/6028395/3895e63e-abb7-11e4-9587-de40d9643308.png)

**Comment by yosefw** [comment]
+1

**Comment by christiangenco** [comment]
This should probably be redone for [Github Pages](https://pages.github.com/) - hosting is free and guaranteed.

**Comment by pixelsign** [comment]
Thank you for the heads up. The demo now works under the Github pages.

http://pixelsign.github.io/html5-device-mockups/
