### ISSUE TITLE
Hiding div on generator

### ISSUE THREAD

**Issue by 2braincells2go** [pixelsign/html5-device-mockups#18]
Firstly, thank you for sharing this, really nice!

Was wanting to use this in classroom project and stumped, but that not hard to do:)

On the "Mockup Device Generator.html" page: is there an easy way to simply hide the div with the generated code? Would like to use the page as a real mockup viewer. In other words display no code, just let users click on the buttons to view a site.

Thanks in advance!

Woody

**Comment by pixelsign** [comment]
Changed the site a bit but the demo still contains the div with the code. You can simply download it and remove it.
