### ISSUE TITLE
Photoshop PSD as "png"

### ISSUE THREAD

**Issue by acidus99** [pixelsign/html5-device-mockups#20]
In your most recent update, you several of the PNG images are actually Adobe Photoshop PSD files. Looks like you did a "Save As..." and saved a PSD with a ".png" extension instead of a PNG export. Opening these in a basic image viewer/editor will yield an error about the file being corrupted, because these aren't actually PNG images.

There could be more, I just happened to notice it for the Galaxy S5 images. I used the 'file' command (native to Linux, Mac, other Unix-like systems) to detect the mismatches:

MacMini:galaxy_s5 billy$ file *
galaxy.psd:               Adobe Photoshop Image, 1239 x 2406, RGBA, 4x 8-bit channels
galaxy_s5_land_black.png: Adobe Photoshop Image, 2406 x 1239, RGBA, 4x 8-bit channels
galaxy_s5_land_gold.png:  Adobe Photoshop Image, 2406 x 1239, RGBA, 4x 8-bit channels
galaxy_s5_land_white.png: Adobe Photoshop Image, 2406 x 1239, RGBA, 4x 8-bit channels
galaxy_s5_port_black.png: PNG image data, 1239 x 2406, 8-bit/color RGBA, interlaced
galaxy_s5_port_gold.png:  PNG image data, 1239 x 2406, 8-bit/color RGBA, interlaced
galaxy_s5_port_white.png: PNG image data, 1239 x 2406, 8-bit/color RGBA, interlaced

**Comment by pixelsign** [comment]
Sorry for the huge delay, it is fixed now.

**Comment by acidus99** [comment]
Hurray! Glad you fixed it
