### ISSUE TITLE
Device doesn't appear

### ISSUE THREAD

**Issue by Hayko1994** [pixelsign/html5-device-mockups#36]
Hi. I've added CSS file which was mentioned in the documentation. Also added HTML code which was generated by the device while the device doesn't appear. The part of the page where it should appear is empty. Can you help me to solve that problem? Thanks

**Comment by ben182** [comment]
Hi
can you explain your problem a bit further and give some code examples?

**Comment by Hayko1994** [comment]
Hi. I solve that problem however can't control the size of the device. on the small screens it seems normal but on the large screen it looks like this. How can I control the size of the device? Here are the 2 images.
![demo2](https://cloud.githubusercontent.com/assets/22639899/25303931/cc51a4b0-276d-11e7-83e8-3dc49e2cedea.jpg)
![demo1](https://cloud.githubusercontent.com/assets/22639899/25303932/cc54fb9c-276d-11e7-913e-c1195dd90a15.jpg)

**Comment by ben182** [comment]
You can control the height by setting a `max-width` in the `.device-container`. For example 300px. This will also make it responsive for small screens.
