### ISSUE TITLE
iPhone 8 and iPhone X

### ISSUE THREAD

**Issue by davidtmiller** [pixelsign/html5-device-mockups#56]
Excellent tool, thank you guys so much for developing device mockups! Are there any plans to add the iPhone 8 and iPhone X to the lineup? Is there anything I can do to help? Thanks again!

**Comment by pixelsign** [comment]
Good idea, will add soon!

**Comment by gerbil802** [comment]
Any update on this?

**Comment by ben182** [comment]
Sadly not. We need a good mockup. Feel free to commit one as I added the help wanted flag.

**Comment by kajensen** [comment]
+1

**Comment by mehrdadrafiee** [comment]
Nice work! Cannot wait for these mockups to be added. 👍

**Comment by RigoTheCEO** [comment]
Any updates?

**Comment by pshah123** [comment]
iPhone X is available via #69 🎉

**Comment by srigaux** [comment]
https://github.com/pixelsign/html5-device-mockups/pull/72
