### ISSUE TITLE
Is it legal to use Apple-logo as a part of an mockup in a website?

### ISSUE THREAD

**Issue by rranke** [pixelsign/html5-device-mockups#61]
Are there any experiences in about: 

1. generally, if it is legal to use device-mockups, by using the original products as images?

2. particularly when using mockups showing the Apple-Logo? 
( https://github.com/pixelsign/html5-device-mockups/blob/master/device-mockups/iMac/portrait_black.png )

**Comment by pixelsign** [comment]
This might be helpful
