### ISSUE TITLE
The license information for this library

### ISSUE THREAD

**Issue by ralphchung** [pixelsign/html5-device-mockups#63]
Hi @pixelsign ,
I am a contributor of cdnjs and willing to host this library.
In [```LICENSE.txt```](https://github.com/pixelsign/html5-device-mockups/blob/master/LICENSE.txt), the license is MIT, but in [```package.json```](https://github.com/pixelsign/html5-device-mockups/blob/master/package.json#L10), the license field is ISC. The information does not correspond. Could you let me know which license are you using?

If you have any suggestions, please let me know.
Thank you.

[cdnjs/cdnjs#12283](https://github.com/cdnjs/cdnjs/issues/12283)

**Comment by ben182** [comment]
Hi ralphchung,

we use the MIT license. I changed the package.json.

Cheers Ben
