### ISSUE TITLE
Can not reach to the content inside mockup

### ISSUE THREAD

**Issue by emrealparslan93** [pixelsign/html5-device-mockups#68]
Hello, I'm trying to click to button inside mockup but I couldn't reach to the button. Tried z-index but didn't help. Could you tell me how can I reach to content inside mockup?

**Comment by emrealparslan93** [comment]
I found the solution:

For 'screen' div, you have to set `pointer-events: all`.

**Comment by jonsken** [comment]
Hi, I am trying to show a video inside the mockup, but nothing (video controls, buttons or text) is reachable inside the wrapper. Even if I set `.device .screen { ...  pointer-events: auto }` to `pointer-events: all`. 
Any ideas?
