### ISSUE TITLE
Demo Page not working

### ISSUE THREAD

**Issue by theluk** [pixelsign/html5-device-mockups#73]
![image](https://user-images.githubusercontent.com/580946/50906906-678b3580-1426-11e9-8bc6-95bff2f662b4.png)

**Comment by theluk** [comment]
On Chrome 71.0.3578.98 without any plugins or extensions

**Comment by itsminetechnology101** [comment]
I had a similar problem. A background color from a div was overlaying the phone image. I changed the z-index of the covering div and it got fixed. In the css for the mockups the z-index is set to -1. I experimented with the div with the background color changing its z-index until it showed the phones. In my case I set the div z-index to 1.

**Comment by binakot** [comment]
Same problem on chrome 72.0.3626.121

**Comment by dieguason** [comment]
I had same problem. I solved it adding "z-index: 10" to #device div.

Eg:
`<div class="device" data-device="iPhoneX" data-orientation="landscape" data-color="black"  style="z-index: 10">`

Of course u can put another number to z-index in order to be at the top of all divs.

**Comment by Enigma644** [comment]
Bump. Any ETA on a proper fix?

**Comment by biapar** [comment]
Not work

**Comment by CR34L** [comment]
Same here. Tested with Safari & Firefox (without any extensions).

**Comment by gustsu** [comment]
I've fixed this issue in my PR here: #76  Just waiting for it to be approved and merged by @pixelsign

**Comment by pixelsign** [comment]
Merged the PR now
